import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import MainProvider from "../../providers/MainProvider";
import NavbarComp from "../../components/layout/NavbarComp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainProvider>
          <NavbarComp />
          <main className="">{children}</main>
        </MainProvider>
      </body>
    </html>
  );
}
