import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css";

import MainProvider from "../../../providers/MainProvider";
import NavbarComp from "../../../components/layout/NavbarComp";
import Footer from "../../../components/layout/Footer";
import { NextIntlClientProvider, useMessages } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bruno Maruya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className="">
        <MainProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <NavbarComp />
            <main className="margin min-h-screen ">{children}</main>
            <Footer />
          </NextIntlClientProvider>
        </MainProvider>
      </body>
    </html>
  );
}
